import type { LabSystemManifest } from '@/tools/lab-kit/systemManifest';

// Only documented implementation files are available on demand; no eager whole-Core source bundle.
const sources = import.meta.glob<string>([
  '../../../core/map/dungeonMapPresetRepository.ts',
  '../../../core/dungeon-runtime/dungeonRuntimeAssembly.ts',
  '../../../core/scene/createDungeonMapSceneEnvironment.ts',
  '../../../core/dungeon-runtime-save/dungeonRuntimeSave.ts',
  '../../../core/scene/dungeonMapSceneLayout.ts',
  '../../../core/dungeon-traversal/dungeonTraversal.ts',
  '../../../core/dungeon-movement/dungeonMovementResolver.ts',
  '../../../core/dungeon-player-movement/dungeonPlayerSystem.ts',
  '../../../core/dungeon-player-movement/dungeonPlayerStepEvents.ts',
  '../../../core/dungeon-agent/dungeonAgentSystem.ts',
  '../../../core/dungeon-agent/dungeonAgent.controllers.ts',
  '../../../core/dungeon-transition/dungeonTransition.ts',
  '../../../core/dungeon-transition/dungeonTransition.document.ts',
  '../../../core/dungeon-obstacle/dungeonObstacle.ts',
  '../../../core/dungeon-player-spawn/dungeonPlayerSpawn.document.ts',
  '../../../core/dungeon-runtime/dungeonRuntime.types.ts',
  '../../../core/camera/cameraLabController.ts',
  '../../../core/dungeon-view/dungeonOverheadView.ts',
  '../../../core/render-deformation/deformation.ts',
], { query: '?raw', import: 'default' });
const core = (path: string, symbols: string, purpose: string) => ({
  path: 'core/' + path, symbols, purpose, loadSource: sources['../../../core/' + path],
});
const manifest = (
  kind: LabSystemManifest['kind'], responsibility: string,
  refs: LabSystemManifest['core'], services: readonly string[], protocols: readonly string[], scheduling: string,
): LabSystemManifest => Object.freeze({ kind, responsibility, core: refs, services, protocols, scheduling });

/** Contract documentation belongs to the catalog, not duplicated in individual panels.
 * dependencies and actual scheduled tasks are read from the module/runner directly.
 */
export const dungeonSystemManifests: Readonly<Record<string, LabSystemManifest>> = {
  'dungeon-libraries': manifest('system', '读取地图、场景环境与阴影配置库',
    [core('map/dungeonMapPresetRepository.ts', '地图预设仓库', '读取地图配置')],
    ['提供 dungeon:libraries'], ['处理地图目录查询'], 'start 异步读取；不注册周期任务'),
  'dungeon-map-loader': manifest('system', '准备并提交地图 Session；仅装配已安装的 Core 工厂',
    [core('dungeon-runtime/dungeonRuntimeAssembly.ts', 'DungeonRuntimeAssembly', '显式系统安装、候选 Runtime 准备'),
     core('scene/createDungeonMapSceneEnvironment.ts', 'createDungeonDocumentSceneEnvironmentAsync', '地图场景资源'),
     core('dungeon-runtime-save/dungeonRuntimeSave.ts', 'applyDungeonRuntimeSaveState', '恢复运行态')],
    ['提供 dungeon:map-loader-references', '提供 dungeon:runtime-assembly', '提供场景对象显示 View', '读取配置库'],
    ['处理 dungeon.map.switch / dungeon.runtime.commit', '观察通知 dungeon.map.changed / dungeon.runtime.changed'],
    '命令触发异步准备；必需 Core 准备成功后提交；广播只负责观察'),
  'dungeon-config': manifest('configuration', '选择初始地图与手动切图',
    [], ['通过协议访问地图目录和 Loader'], ['请求 dungeon.map.switch'], 'start 初次加载；用户操作触发'),
  'dungeon-grid': manifest('debug', '查看地图格坐标与世界布局；提供格子 Debug 视图',
    [core('scene/dungeonMapSceneLayout.ts', 'resolveDungeonMapTileWorldLayout', '格子世界布局')],
    ['读取地图 Reader', '提供格子 View Consumer'], ['消费 dungeon.map.changed'], '切图或显示设置变化时更新'),
  'dungeon-grid-debug': manifest('compatibility', '旧格子模块 ID 的兼容入口', [], [], [], '无独立运行任务'),
  'dungeon-traversal': manifest('system', '安装通行世界工厂，维护实占位与路径软预约',
    [core('dungeon-traversal/dungeonTraversal.ts', 'createDungeonTraversalWorld / DungeonTraversalWorld', '通行与占位权威')],
    ['向 runtime-assembly 安装 traversal', '提供通行 Debug View'], ['Core subscribe → dungeon.traversal.changed'],
    'Session 准备时创建；变化触发，Debug 合并刷新'),
  'dungeon-movement': manifest('system', '安装共享移动仲裁器，管理移动预留、提交与回退',
    [core('dungeon-movement/dungeonMovementResolver.ts', 'createDungeonMovementResolver / DungeonMovementResolver', '移动请求与冲突仲裁')],
    ['向 runtime-assembly 安装 movement', '使用通行世界', '提供移动 Debug View'],
    ['Core subscribe → dungeon.movement.changed'], '动作由玩家/Agent 推进；Debug 在 debug 阶段合并与限频'),
  'player-movement': manifest('system', '玩家输入命令、连续移动与格步规则边界',
    [core('dungeon-player-movement/dungeonPlayerSystem.ts', 'DungeonPlayerSystem', '独立于 DOM 的玩家命令、推进与格步事实'),
     core('dungeon-player-movement/dungeonPlayerStepEvents.ts', 'DungeonPlayerStepEvents', '不可变格步事实与同步规则顺序')],
    ['读取地图 Reader 与移动能力', '提供 dungeon:player-step-rules', '提供阻挡尝试处理与玩家 View'],
    ['同步 PlayerStepCompleted：传送 100 → Agent 200', '观察事件 dungeon.player.step-completed', '请求 dungeon.runtime.commit'],
    'simulation / 100；完成事实处理后才允许续步；输入适配仍由 Lab 提供'),
  'dungeon-agent': manifest('system', '准备 Agent 状态，执行移动与控制器决策',
    [core('dungeon-agent/dungeonAgentSystem.ts', 'DungeonAgentSystem', '独立于 DOM 的 Agent 生命周期与更新'),
     core('dungeon-agent/dungeonAgent.controllers.ts', 'updateDungeonAgentControllers / runDungeonAgentControllersAfterPlayerStep', 'AI 与路径规划')],
    ['读取 runtime-assembly、玩家格步与俯视显示服务', '提供 Agent Runtime Reader'],
    ['同步消费 PlayerStepCompleted / 200', '发布 Agent loaded / changed 观察通知'],
    '候选 Session 提交前准备；simulation / 200；活动动作增量推进，连续决策默认 100ms 一次'),
  'dungeon-transition': manifest('system', '消费交互与格步事实，协调地图传送',
    [core('dungeon-transition/dungeonTransition.ts', 'createDungeonTransitionController', '传送流程'),
     core('dungeon-transition/dungeonTransition.document.ts', 'findDungeonDocumentExitAfterMovement', '出口判定')],
    ['读取地图、配置库、玩家格步、阻挡服务与俯视显示服务'],
    ['同步消费 PlayerStepCompleted / 100，可停止续步', '请求 dungeon.map.switch', '发布传送生命周期观察事件'],
    '事件触发；不轮询玩家位置；输入锁覆盖切换过程'),
  'dungeon-obstacle': manifest('system', '安装地图障碍扫描与状态能力，并提供启停和 Debug',
    [core('dungeon-obstacle/dungeonObstacle.ts', '障碍状态 API', '权威阻碍状态修改')],
    ['向 runtime-assembly 安装 obstacles', '读取地图与可用通行状态', '提供障碍 View'], ['消费通行变化，提交 runtime.commit'], '用户操作和障碍变化触发'),
  'player-spawn': manifest('debug', '查看地图解析出的出生点',
    [core('dungeon-player-spawn/dungeonPlayerSpawn.document.ts', 'resolveDungeonDocumentPlayerSpawn', '由 Loader 使用的出生点解析')],
    ['读取地图 Reader'], ['消费 dungeon.map.changed'], '切图触发'),
  'dungeon-runtime': manifest('debug', '观察当前 Runtime，不创建第二份 Runtime',
    [core('dungeon-runtime/dungeonRuntime.types.ts', 'DungeonRuntime', '状态契约')],
    ['读取地图 Reader'], ['消费地图与 Runtime 观察通知'], '事件触发'),
  'dungeon-runtime-save-switch': manifest('configuration', '人工切图与查看存档',
    [core('dungeon-runtime-save/dungeonRuntimeSave.ts', '运行态存取', '由 Loader 管理')],
    ['通过 Loader 协议操作'], ['请求存档与地图切换'], '用户操作与状态通知触发'),
  'dungeon-player-camera': manifest('system', '将玩家姿态映射到公共相机',
    [core('camera/cameraLabController.ts', 'CameraLabController', '相机控制'),
     core('dungeon-view/dungeonOverheadView.ts', 'View Consumer', '显示映射')],
    ['读取地图 Reader', '提供玩家相机服务和 View'], ['消费地图变化，发布相机模式变化'],
    'presentation / 100；相机连续平滑；Debug 折叠时停止生成 JSON'),
  'dungeon-first-person-camera': manifest('compatibility', '旧玩家相机 ID；依赖新模块，不重复安装系统',
    [core('camera/cameraLabController.ts', 'CameraLabController', '共享相机')], ['同玩家相机'], ['同玩家相机'], '无独立任务；由 dungeon-player-camera 安装实现'),
  'dungeon-overhead-view': manifest('system', '协调俯视显示配置及消费者映射',
    [core('dungeon-view/dungeonOverheadView.ts', '俯视配置与控制句柄', '显示变换')],
    ['读取玩家相机、场景对象及各 Debug View Consumer', '提供 dungeon:overhead-view'], ['消费地图及相机模式变化'], '配置或模式变化触发'),
  'dungeon-visual-deformation': manifest('system', '协调可选物体视觉变形',
    [core('render-deformation/deformation.ts', '视觉变形控制', '渲染对象显示映射')],
    ['读取俯视服务与地图 Reader', '提供变形设置服务'], ['订阅俯视配置与地图变化'], '配置变化触发'),
  'viewport-layers': manifest('debug', '演示工作台覆盖层', [], ['使用 Host Viewport'], [], '用户操作触发'),
};
