import { useEffect, useRef, useState } from 'react';
import { ArcRotateCamera, Color3, Color4, Engine, HemisphericLight, MeshBuilder, Scene, StandardMaterial, Vector3 } from '@babylonjs/core';
import { createDefaultModelSwingConfig, createModelEntity, loadModelSwingConfigLibrary, saveModelSwingConfigLibrary, type ModelEntity, type ModelSwingConfig, type ModelSwingConfigLibrary } from '@/core/model';
import { loadModelAssetManifestByExtension } from '@/core/resources';

const rad = Math.PI / 180;
const focusModel = (camera: ArcRotateCamera, model: ModelEntity) => {
  const meshes = model.meshes.filter((mesh) => mesh.getTotalVertices() > 0);
  if (!meshes.length) return;
  let min = new Vector3(Infinity, Infinity, Infinity); let max = new Vector3(-Infinity, -Infinity, -Infinity);
  for (const mesh of meshes) { mesh.computeWorldMatrix(true); const box = mesh.getBoundingInfo().boundingBox; min = Vector3.Minimize(min, box.minimumWorld); max = Vector3.Maximize(max, box.maximumWorld); }
  const center = min.add(max).scale(0.5); const size = Math.max(Vector3.Distance(min, max), 0.05);
  camera.setTarget(center); camera.radius = size * 2.3; camera.minZ = Math.max(size / 1000, 0.0001); camera.maxZ = Math.max(size * 1000, 100);
};

export const ModelSwingLab = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null); const sceneRef = useRef<Scene | null>(null); const cameraRef = useRef<ArcRotateCamera | null>(null); const modelRef = useRef<ModelEntity | null>(null); const configRef = useRef<ModelSwingConfig>(createDefaultModelSwingConfig('')); const libraryRef = useRef<ModelSwingConfigLibrary>({});
  const [assets, setAssets] = useState<string[]>([]); const [selectedPath, setSelectedPath] = useState(''); const [config, setConfig] = useState(createDefaultModelSwingConfig('')); const [status, setStatus] = useState('正在初始化…'); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false);

  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas) return; const engine = new Engine(canvas, true, { stencil: true }); const scene = new Scene(engine); scene.clearColor = new Color4(0.025, 0.035, 0.052, 1); const camera = new ArcRotateCamera('model_swing_camera', -Math.PI / 2, Math.PI / 2.5, 6, Vector3.Zero(), scene); camera.attachControl(canvas, true); camera.wheelPrecision = 35; const light = new HemisphericLight('model_swing_light', new Vector3(0.4, 1, 0.25), scene); light.intensity = 1.45; const ground = MeshBuilder.CreateGround('model_swing_ground', { width: 30, height: 30 }, scene); const material = new StandardMaterial('model_swing_ground_material', scene); material.diffuseColor = new Color3(0.07, 0.095, 0.14); material.specularColor = Color3.Black(); ground.material = material; sceneRef.current = scene; cameraRef.current = camera;
    let elapsed = 0; engine.runRenderLoop(() => { const model = modelRef.current; const current = configRef.current; elapsed += engine.getDeltaTime() / 1000; if (model) { const center = (current.minAngleDeg + current.maxAngleDeg) / 2; const amplitude = (current.maxAngleDeg - current.minAngleDeg) / 2; const swing = current.enabled ? center + amplitude * Math.sin(elapsed * current.frequencyHz * Math.PI * 2 + current.phaseDeg * rad) : 0; const rotation = { ...current.baseRotationDeg, [current.axis]: current.baseRotationDeg[current.axis] + swing }; model.root.rotation.set(rotation.x * rad, rotation.y * rad, rotation.z * rad); } scene.render(); }); const resize = () => engine.resize(); window.addEventListener('resize', resize); return () => { window.removeEventListener('resize', resize); modelRef.current?.dispose(); scene.dispose(); engine.dispose(); };
  }, []);

  useEffect(() => { void loadModelSwingConfigLibrary().then((library) => { libraryRef.current = library; if (selectedPath && library[selectedPath]) { configRef.current = library[selectedPath]; setConfig(library[selectedPath]); } }).catch((error: unknown) => setStatus(error instanceof Error ? error.message : String(error))); }, [selectedPath]);
  useEffect(() => { loadModelAssetManifestByExtension(/\.(glb|gltf)$/i).then((glb) => { const first = glb[0] ?? ''; const next = libraryRef.current[first] ?? createDefaultModelSwingConfig(first); setAssets(glb); setSelectedPath(first); configRef.current = next; setConfig(next); setStatus(glb.length ? `发现 ${glb.length} 个可配置模型` : '没有发现 GLB/GLTF 模型'); }).catch((error: unknown) => setStatus(error instanceof Error ? error.message : String(error))); }, []);
  useEffect(() => { if (!selectedPath || !sceneRef.current || !cameraRef.current) return; let cancelled = false; setLoading(true); modelRef.current?.dispose(); modelRef.current = null; void createModelEntity(sceneRef.current, selectedPath, { autoPlayAnimation: true }).then((model) => { if (cancelled) return model.dispose(); model.root.rotationQuaternion = null; modelRef.current = model; focusModel(cameraRef.current!, model); setStatus(`正在挥动：${decodeURIComponent(selectedPath.split('/').pop() ?? selectedPath)}`); }).catch((error: unknown) => setStatus(error instanceof Error ? `加载失败：${error.message}` : String(error))).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [selectedPath]);

  const selectModel = (path: string) => { const next = libraryRef.current[path] ?? createDefaultModelSwingConfig(path); configRef.current = next; setConfig(next); setSelectedPath(path); };
  const update = (patch: Partial<ModelSwingConfig>) => { const next = { ...config, ...patch, modelPath: selectedPath }; configRef.current = next; setConfig(next); libraryRef.current = { ...libraryRef.current, [selectedPath]: next }; };
  const updateRotation = (axis: 'x' | 'y' | 'z', value: number) => { if (Number.isFinite(value)) update({ baseRotationDeg: { ...config.baseRotationDeg, [axis]: value } }); };
  const save = async () => { if (!selectedPath || saving) return; setSaving(true); try { await saveModelSwingConfigLibrary(libraryRef.current); setStatus(`已保存 ${Object.keys(libraryRef.current).length} 个模型的挥动配置`); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } finally { setSaving(false); } };
  const reset = () => { const next = createDefaultModelSwingConfig(selectedPath); configRef.current = next; setConfig(next); libraryRef.current = { ...libraryRef.current, [selectedPath]: next }; };

  return <main className="model-swing-lab"><header><div><h1>3D 模型挥动动画 Lab</h1><span>{status}</span></div><select aria-label="选择模型" value={selectedPath} onChange={(event) => selectModel(event.target.value)}><option value="">选择 GLB/GLTF 模型…</option>{assets.map((path) => <option key={path} value={path}>{decodeURIComponent(path.replace('/resources/', ''))}</option>)}</select><button disabled={!selectedPath || saving} onClick={() => void save()}>{saving ? '保存中…' : '保存 Config'}</button></header><section className="viewport"><canvas ref={canvasRef} /><div>左键旋转视角 · 右键平移 · 滚轮缩放</div></section><aside><h2>挥动参数</h2><p>{loading ? '正在加载模型…' : decodeURIComponent(selectedPath.replace('/resources/', ''))}</p><label className="check"><span>启用挥动</span><input type="checkbox" checked={config.enabled} onChange={(event) => update({ enabled: event.target.checked })} /></label><label><span>挥动轴</span><select aria-label="挥动轴" value={config.axis} onChange={(event) => update({ axis: event.target.value as ModelSwingConfig['axis'] })}><option value="x">X</option><option value="y">Y</option><option value="z">Z</option></select></label><NumberControl label="基础角度 X" value={config.baseRotationDeg.x} onChange={(value) => updateRotation('x', value)} /><NumberControl label="基础角度 Y" value={config.baseRotationDeg.y} onChange={(value) => updateRotation('y', value)} /><NumberControl label="基础角度 Z" value={config.baseRotationDeg.z} onChange={(value) => updateRotation('z', value)} /><NumberControl label="最小挥动角度" value={config.minAngleDeg} onChange={(minAngleDeg) => update({ minAngleDeg })} /><NumberControl label="最大挥动角度" value={config.maxAngleDeg} onChange={(maxAngleDeg) => update({ maxAngleDeg })} /><NumberControl label="频率 Hz" value={config.frequencyHz} min={0.01} max={30} step={0.1} onChange={(frequencyHz) => update({ frequencyHz })} /><NumberControl label="相位角度" value={config.phaseDeg} onChange={(phaseDeg) => update({ phaseDeg })} /><small>最小/最大角度决定挥动范围，频率决定每秒挥动次数。</small><button className="reset" disabled={!selectedPath} onClick={reset}>恢复该模型默认值</button></aside></main>;
};

const NumberControl = ({ label, value, min = -360, max = 360, step = 1, onChange }: { label: string; value: number; min?: number; max?: number; step?: number; onChange: (value: number) => void }) => <label><span>{label}</span><input aria-label={label} type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Number(event.target.value))} /></label>;
