export const GAME_EVENTS = Object.freeze({
  PAUSED: "game:paused",
  RESUMED: "game:resumed",
  FPS_CHANGED: "game:fpsChanged",
  GAME_RESET: "game:reset",
  INPUT_TRIGGER: "input:trigger",
  INPUT_CONFIRM: "input:confirm",
  RHYTHM_TEST_TRIGGER: "rhythm:testTrigger",
  RHYTHM_START: "rhythm:start",
  RHYTHM_JUDGE_TRIGGERED: "rhythm:judgeTriggered",
  RHYTHM_NOTE_PERFECT: "rhythm:notePerfect",
  RHYTHM_NOTE_GREAT: "rhythm:noteGreat",
  RHYTHM_NOTE_HIT: "rhythm:noteHit",
  RHYTHM_NOTE_MISS: "rhythm:noteMiss",
  DIALOGUE_LINE_CHANGED: "dialogue:lineChanged",
  DIALOGUE_HISTORY_REQUESTED: "dialogue:historyRequested",
  ENTITY_UPDATED: "entity:updated",
  OBJECT_ADDED: "entity:added",
  OBJECT_REMOVED: "entity:removed",
  DEBUG_LAYER_TOGGLED: "debug:layerToggled",
  SCREENSHOT_CAPTURED: "debug:screenshotCaptured"
});
