import type { MonsterDeathParameterValues, MonsterDeathVisualDefinition } from '@/core/monster-death-motion/types.ts';
import type { SpriteAshPreset } from '@/core/sprite/ash/spriteAsh.types.ts';
import type { SpriteNoiseErodeOptions } from '@/core/sprite/shader/modules/noiseErode.module.ts';

const numberValue = (values: MonsterDeathParameterValues, key: string, fallback: number): number => {
  const value = Number(values[key]);
  return Number.isFinite(value) ? value : fallback;
};

export const resolveSpriteDissolveProgress = (progress: number, parameters: MonsterDeathParameterValues): number => {
  const start = numberValue(parameters, 'dissolveStart', 0);
  return Math.max(0, Math.min(1, (progress - start) / Math.max(.001, 1 - start)));
};

export const createSpriteDissolveOptions = (
  visual: MonsterDeathVisualDefinition,
  parameters: MonsterDeathParameterValues,
  progress = 0
): SpriteNoiseErodeOptions => ({
  enabled: true,
  progress,
  directionalStrength: visual.spriteEffect?.pattern === 'void' ? 0 : 1,
  radialStrength: visual.spriteEffect?.pattern === 'void' ? 1 : 0,
  radialDirection: 1,
  centerX: 0,
  centerY: 0,
  radialScaleX: 1,
  radialScaleY: 1,
  radialRotationDeg: 0,
  radialPower: 1,
  radialNoiseStrength: .2,
  radialNoiseScale: 6,
  crystalStrength: visual.spriteEffect?.pattern === 'frost' ? 1 : 0,
  crystalScale: 8,
  crystalSharpness: .5,
  crystalAspect: 1,
  crystalRotationDeg: 0,
  crystalCrackWidth: .035,
  crystalJitter: .12,
  crystalBranchStrength: .35,
  crystalBranchScale: 1.7,
  spiralStrength: visual.spriteEffect?.pattern === 'void' ? .75 : 0,
  spiralTurns: 3,
  spiralSpeed: 2.5,
  spiralDirection: 1,
  spiralRadialFrequency: 18,
  voidPullStrength: visual.spriteEffect?.pattern === 'void' ? .8 : 0,
  voidPullRadius: .72,
  voidPullFalloff: .67,
  voidPullPower: 2,
  directionAngleDeg: 90,
  noiseScale: 7,
  noiseStrength: .62,
  noiseSpeed: .08,
  noiseDetail: .72,
  noiseRoughness: .5,
  noiseAspect: 1,
  noiseRotationDeg: 0,
  noiseFlowAngleDeg: 90,
  warpStrength: 0,
  warpScale: 4,
  warpSpeed: .05,
  edgeWidth: .11,
  edgeSoftness: .025,
  edgeColor: '#ffb45b',
  edgeIntensity: 1.35,
  edgeInnerWidth: .32,
  edgeOuterWidth: 1,
  edgeInnerColor: '#fff1c7',
  edgeOuterColor: '#ffb45b',
  edgeFalloffPower: 1,
  edgeNoiseStrength: .08,
  edgeNoiseScale: 18,
  edgePulseStrength: .12,
  edgePulseSpeed: 7,
  residueWidth: .18,
  residueOpacity: .22,
  residueColor: '#4a4038',
  residueDensity: .55,
  residueNoiseScale: 24,
  residueDecayPower: 1.4,
  residueFadeStart: .82,
  residueGlow: 0,
  vertexDeformStrength: 0,
  vertexBendX: 0,
  vertexBendY: 0,
  vertexTwist: 0,
  vertexBulge: 0,
  vertexDepth: 0,
  vertexWaveStrength: 0,
  vertexWaveScale: 8,
  vertexWaveSpeed: 3,
  vertexAnchorY: 0,
  vertexSubdivisions: 12,
  rise: numberValue(parameters, 'rise', 2.6),
  driftX: 0,
  turbulence: numberValue(parameters, 'flutter', .28),
  ashColor: typeof parameters.ashColor === 'string' ? parameters.ashColor : '#b8b8b8',
  ashTrail: .3,
  ashDensity: 1,
  ashOpacity: .9,
  flickerSpeed: 6,
  alphaCutoff: .01,
  charColor: typeof parameters.ashColor === 'string' ? parameters.ashColor : '#242424',
  charStrength: numberValue(parameters, 'ashStrength', .9),
  seed: 1
});

export const createSpriteDeathParticlePreset = (
  visual: MonsterDeathVisualDefinition,
  parameters: MonsterDeathParameterValues,
  duration: number
): SpriteAshPreset => ({
  presetKey: `spriteDeath_${visual.spriteEffect?.pattern ?? 'ash'}`,
  name: 'Sprite death edge particles',
  particleMode: visual.particles?.presetKey === 'blackShards' || visual.particles?.presetKey === 'embers' || visual.particles?.presetKey === 'pixel' ? visual.particles.presetKey : 'ash',
  duration,
  progressPower: 1,
  startHold: 0,
  endFade: .04,
  fieldBlendMode: 'weighted',
  fieldInvert: 0,
  fieldContrast: 1,
  fieldOffset: 0,
  directionAngleDeg: 90,
  directionalStrength: visual.spriteEffect?.pattern === 'void' ? 0 : 1,
  radialStrength: visual.spriteEffect?.pattern === 'void' ? 1 : 0,
  radialDirection: 1,
  centerX: 0,
  centerY: 0,
  radialScaleX: 1,
  radialScaleY: 1,
  radialRotationDeg: 0,
  radialPower: 1,
  radialNoiseStrength: .2,
  radialNoiseScale: 6,
  crystalStrength: visual.spriteEffect?.pattern === 'frost' ? 1 : 0,
  crystalScale: 8,
  crystalSharpness: .5,
  crystalAspect: 1,
  crystalRotationDeg: 0,
  crystalCrackWidth: .035,
  crystalJitter: .12,
  crystalBranchStrength: .35,
  crystalBranchScale: 1.7,
  spiralStrength: visual.spriteEffect?.pattern === 'void' ? .75 : 0,
  spiralTurns: 3,
  spiralSpeed: 2.5,
  spiralDirection: 1,
  spiralRadialFrequency: 18,
  voidPullStrength: visual.spriteEffect?.pattern === 'void' ? .8 : 0,
  voidPullRadius: .72,
  voidPullFalloff: .67,
  voidPullPower: 2,
  noiseScale: 7,
  noiseStrength: .62,
  noiseSpeed: .08,
  noiseDetail: .72,
  noiseRoughness: .5,
  noiseAspect: 1,
  noiseRotationDeg: 0,
  noiseFlowAngleDeg: 90,
  warpStrength: 0,
  warpScale: 4,
  warpSpeed: .05,
  edgeWidth: .1,
  edgeSoftness: .025,
  edgeColor: '#ffb45b',
  edgeIntensity: 1.4,
  edgeInnerWidth: .32,
  edgeOuterWidth: 1,
  edgeInnerColor: '#fff1c7',
  edgeOuterColor: '#ffb45b',
  edgeFalloffPower: 1,
  edgeNoiseStrength: .08,
  edgeNoiseScale: 18,
  edgePulseStrength: .12,
  edgePulseSpeed: 7,
  residueWidth: .18,
  residueOpacity: .22,
  residueColor: '#4a4038',
  residueDensity: .55,
  residueNoiseScale: 24,
  residueDecayPower: 1.4,
  residueFadeStart: .82,
  residueGlow: 0,
  vertexDeformStrength: 0,
  vertexBendX: 0,
  vertexBendY: 0,
  vertexTwist: 0,
  vertexBulge: 0,
  vertexDepth: 0,
  vertexWaveStrength: 0,
  vertexWaveScale: 8,
  vertexWaveSpeed: 3,
  vertexAnchorY: 0,
  vertexSubdivisions: 12,
  charColor: '#202020',
  particleRate: 220,
  particleStartProgress: 0,
  particleEndProgress: .985,
  particleRatePower: 1,
  particleLifeMin: .45,
  particleLifeMax: 1.15,
  particlePowerMin: .25,
  particlePowerMax: .72,
  particleSizeMin: .25,
  particleSizeMax: .72,
  particleGravityX: 0,
  particleGravityY: .16,
  particleGravityZ: 0,
  particleAngularSpeedMin: -5,
  particleAngularSpeedMax: 5,
  charStrength: .85,
  ashColor: typeof parameters.ashColor === 'string' ? parameters.ashColor : '#b8b8b8',
  ashTrail: .3,
  ashDensity: 1,
  ashOpacity: .9,
  rise: numberValue(parameters, 'rise', 2.6),
  driftX: 0,
  turbulence: numberValue(parameters, 'flutter', .28),
  flickerSpeed: 6,
  seed: 1,
  alphaCutoff: .01
});
