import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Color3, MeshBuilder, StandardMaterial, TransformNode, Vector3, type Scene } from '@babylonjs/core';
import { createCameraLabController } from '@/core/camera/cameraLabController.ts';
import { createCameraLabScene } from '@/core/scene/createCameraLabScene.ts';
import { createFloatingCameraControlPanel } from '@/core/ui/FloatingCameraControlPanel.ts';
import { requestDevServer } from '@/core/network/devServerPortResolver.ts';
import { MONSTER_CONFIG_URL, MONSTER_STRIPE_PRESET_URL, STRIPE_PRESET_URL, createLayeredMonster, normalizeMonsterConfigLibrary, normalizeMonsterStripePresetLibrary, normalizeStripePresetLibrary, type LayeredMonsterController, type MonsterDisplayConfigLibrary, type MonsterStripePresetLibrary, type StripePresetLibrary } from '@/core/monster';

type Monster = { id:string; monsterConfigKey:string; monsterStripePresetKey:string; positionMode:'grid'|'center'; slots:number; row:number; column:number };
type Battlefield = { id:string; name:string; width:number; cellSize:number; rowSpacing:number; monsters:Monster[] };
type StripeRule = { id:string; startRow:number; monsterStripePresetKey:string };
type MotionConfig = { monsterConfigKey:string; mode:'ghost'|'bigJump'|'hopping'; duration:number; easing:'linear'|'easeInOut'|'easeOutBack'; jumpHeight:number; hopCount:number; floatAmplitude:number; floatCycles:number };
type ActiveMotion = { from:Vector3; to:Vector3; elapsed:number; config:MotionConfig };

const FORMATION_URL='/config/monsterBattlefieldFormations.json', RULE_URL='/config/monsterBattlefieldStripeRules.json', MOVEMENT_URL='/config/monsterMovementConfigs.json', MOVEMENT_API='/api/monster-movement-configs';
const section:React.CSSProperties={padding:12,border:'1px solid #273348',borderRadius:8,background:'#151d29'};
const defaultMotion=(monsterConfigKey:string):MotionConfig=>({monsterConfigKey,mode:'ghost',duration:1.2,easing:'easeInOut',jumpHeight:3,hopCount:3,floatAmplitude:.35,floatCycles:2});
const uid=()=>`monster_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const numberOr=(value:unknown,fallback:number)=>Number.isFinite(Number(value))?Number(value):fallback;
const positiveInt=(value:unknown,fallback=1)=>Math.max(1,Math.round(numberOr(value,fallback)));
const indexInt=(value:unknown,fallback=0)=>Math.max(0,Math.round(numberOr(value,fallback)));
const cloneMonsters=(items:Monster[])=>items.map(item=>({...item}));
const normalizeBattlefield=(value:Partial<Battlefield>,id:string):Battlefield=>({id,name:typeof value.name==='string'?value.name:id,width:positiveInt(value.width,6),cellSize:Math.max(.01,numberOr(value.cellSize,2.5)),rowSpacing:Math.max(.01,numberOr(value.rowSpacing,4)),monsters:Array.isArray(value.monsters)?value.monsters.map((item,index)=>({id:item.id||`${id}_${index}`,monsterConfigKey:item.monsterConfigKey||'',monsterStripePresetKey:item.monsterStripePresetKey||'',positionMode:item.positionMode==='center'?'center':'grid',slots:positiveInt(item.slots),row:indexInt(item.row),column:indexInt(item.column,index)})):[]});
const positionOf=(field:Battlefield,item:Monster)=>new Vector3(item.positionMode==='center'?0:(item.column+item.slots/2-field.width/2)*field.cellSize,0,-item.row*field.rowSpacing);
const displayedPositionOf=(field:Battlefield,item:Monster,config:MonsterDisplayConfigLibrary[string])=>{
 const position=positionOf(field,item);
 position.x+=config.scene3dOffsetX;
 position.y=config.scene3dHeight;
 return position;
};
const stripeForRow=(rules:StripeRule[],row:number,fallback:string)=>rules.slice().sort((a,b)=>a.startRow-b.startRow).reduce((result,rule)=>row+1>=rule.startRow&&rule.monsterStripePresetKey?rule.monsterStripePresetKey:result,fallback);
const easing=(kind:MotionConfig['easing'],t:number)=>kind==='linear'?t:kind==='easeOutBack'?1+2.70158*Math.pow(t-1,3)+1.70158*Math.pow(t-1,2):t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
const fetchJson=async(url:string)=>{const response=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`${url}: HTTP ${response.status}`);return response.json()};
const normalizeMotion=(key:string,value:Partial<MotionConfig>):MotionConfig=>{const base=defaultMotion(key);return{monsterConfigKey:key,mode:value.mode==='bigJump'||value.mode==='hopping'?value.mode:'ghost',duration:Math.max(.05,numberOr(value.duration,base.duration)),easing:value.easing==='linear'||value.easing==='easeOutBack'?value.easing:'easeInOut',jumpHeight:Math.max(0,numberOr(value.jumpHeight,base.jumpHeight)),hopCount:positiveInt(value.hopCount,base.hopCount),floatAmplitude:Math.max(0,numberOr(value.floatAmplitude,base.floatAmplitude)),floatCycles:positiveInt(value.floatCycles,base.floatCycles)}};

const CommitNumberInput:React.FC<{value:number;onCommit:(value:number)=>void;min?:number;step?:number}>=({value,onCommit,min,step})=>{
 const [draft,setDraft]=useState(String(value));const editing=useRef(false);
 useEffect(()=>{if(!editing.current)setDraft(String(value))},[value]);
 const commit=()=>{editing.current=false;const parsed=Number(draft);if(draft.trim()&&Number.isFinite(parsed)){onCommit(parsed);setDraft(String(parsed))}else setDraft(String(value))};
 return <input type="number" min={min} step={step} value={draft} onFocus={()=>{editing.current=true}} onChange={event=>setDraft(event.target.value)} onBlur={commit} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();if(event.key==='Escape'){setDraft(String(value));event.currentTarget.blur()}}}/>;
};

const App:React.FC=()=>{
 const canvasRef=useRef<HTMLCanvasElement>(null),stageRef=useRef<HTMLElement>(null),sceneRef=useRef<Scene|null>(null),gridRef=useRef<TransformNode|null>(null);
 const renderedRef=useRef(new Map<string,LayeredMonsterController>()),motionsRef=useRef(new Map<string,ActiveMotion>());
 const configsRef=useRef<MonsterDisplayConfigLibrary>({}),monsterStripesRef=useRef<MonsterStripePresetLibrary>({}),stripesRef=useRef<StripePresetLibrary>({}),rulesRef=useRef<StripeRule[]>([]);
 const [configs,setConfigs]=useState<MonsterDisplayConfigLibrary>({}),[monsterStripes,setMonsterStripes]=useState<MonsterStripePresetLibrary>({}),[stripes,setStripes]=useState<StripePresetLibrary>({});
 const [battlefields,setBattlefields]=useState<Record<string,Battlefield>>({}),[placements,setPlacements]=useState<Record<string,Monster[]>>({}),[rulesByField,setRulesByField]=useState<Record<string,StripeRule[]>>({}),[movementConfigs,setMovementConfigs]=useState<Record<string,MotionConfig>>({});
 const [activeId,setActiveId]=useState(''),[selectedId,setSelectedId]=useState(''),[message,setMessage]=useState('正在加载配置...');
 const source=battlefields[activeId],field=useMemo(()=>source?{...source,monsters:placements[activeId]||source.monsters}:null,[source,placements,activeId]),selected=field?.monsters.find(item=>item.id===selectedId),rules=rulesByField[activeId]||[],motion=movementConfigs[selected?.monsterConfigKey||'']||defaultMotion(selected?.monsterConfigKey||'');

 useEffect(()=>{Promise.all([fetchJson(MONSTER_CONFIG_URL),fetchJson(MONSTER_STRIPE_PRESET_URL),fetchJson(STRIPE_PRESET_URL),fetchJson(FORMATION_URL),fetchJson(RULE_URL),fetchJson(MOVEMENT_URL)]).then(([rawConfigs,rawMonsterStripes,rawStripes,rawFields,rawRules,rawMovements])=>{
  const nextConfigs=normalizeMonsterConfigLibrary(rawConfigs),nextMonsterStripes=normalizeMonsterStripePresetLibrary(rawMonsterStripes),nextStripes=normalizeStripePresetLibrary(rawStripes),nextFields=Object.fromEntries(Object.entries(rawFields||{}).map(([id,value])=>[id,normalizeBattlefield(value as Partial<Battlefield>,id)]));
  const nextMovements=Object.fromEntries(Object.keys(nextConfigs).map(key=>[key,normalizeMotion(key,rawMovements?.[key]||{})]));
  configsRef.current=nextConfigs;monsterStripesRef.current=nextMonsterStripes;stripesRef.current=nextStripes;setConfigs(nextConfigs);setMonsterStripes(nextMonsterStripes);setStripes(nextStripes);setBattlefields(nextFields);setPlacements(Object.fromEntries(Object.entries(nextFields).map(([id,item])=>[id,cloneMonsters(item.monsters)])));setRulesByField(Object.fromEntries(Object.keys(nextFields).map(id=>[id,Array.isArray(rawRules?.[id]?.rules)?rawRules[id].rules.map((rule:StripeRule)=>({...rule})):[]])));setMovementConfigs(nextMovements);setActiveId(Object.keys(nextFields)[0]||'');setMessage(`已加载 ${Object.keys(nextFields).length} 个战场和 ${Object.keys(nextMovements).length} 个怪物移动配置。`)
 }).catch(error=>setMessage(`加载失败：${String(error)}`))},[]);
 useEffect(()=>{configsRef.current=configs;monsterStripesRef.current=monsterStripes;stripesRef.current=stripes;rulesRef.current=rules},[configs,monsterStripes,stripes,rules]);
 useEffect(()=>{if(field&&!field.monsters.some(item=>item.id===selectedId))setSelectedId(field.monsters[0]?.id||'')},[field,selectedId]);

 useEffect(()=>{
  const canvas=canvasRef.current,stage=stageRef.current;if(!canvas||!stage)return;
  const context=createCameraLabScene(canvas);sceneRef.current=context.scene;context.camera.target.set(0,-1,-8);context.camera.radius=34;
  const camera=createCameraLabController(context.camera),panel=createFloatingCameraControlPanel(stage,camera);gridRef.current=new TransformNode('movementGrid',context.scene);
  const drag={active:false,id:-1,x:0,y:0};
  const down=(event:PointerEvent)=>{if(event.button!==0)return;if(camera.state.lookControlMode==='pointerLock'){void canvas.requestPointerLock?.();return}drag.active=true;drag.id=event.pointerId;drag.x=event.clientX;drag.y=event.clientY;canvas.setPointerCapture(event.pointerId);canvas.style.cursor='grabbing'};
  const move=(event:PointerEvent)=>{if(!drag.active||drag.id!==event.pointerId)return;camera.handlePointerDelta(event.clientX-drag.x,event.clientY-drag.y);drag.x=event.clientX;drag.y=event.clientY;panel.syncFromController()};
  const up=(event:PointerEvent)=>{if(!drag.active||drag.id!==event.pointerId)return;drag.active=false;canvas.style.cursor='grab';if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId)};
  const locked=(event:MouseEvent)=>{if(document.pointerLockElement===canvas)camera.handlePointerDelta(event.movementX,event.movementY)};
  const keyDown=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLSelectElement||!['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE'].includes(event.code))return;camera.keys.add(event.code);event.preventDefault()};
  const keyUp=(event:KeyboardEvent)=>camera.keys.delete(event.code),resize=()=>context.engine.resize();
  const wheel=(event:WheelEvent)=>{if(camera.state.mode==='orbit'){event.preventDefault();camera.handleWheel(event.deltaY);panel.syncFromController()}};
  canvas.style.cursor='grab';canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('wheel',wheel,{passive:false});document.addEventListener('mousemove',locked);window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('resize',resize);
  let time=0;context.engine.runRenderLoop(()=>{const dt=context.engine.getDeltaTime()/1000;time+=dt;camera.update(dt);panel.updateStatus();renderedRef.current.forEach((monster,id)=>{monster.updateTime(time);const active=motionsRef.current.get(id);if(!active)return;active.elapsed+=dt;const raw=Math.min(1,active.elapsed/Math.max(.01,active.config.duration)),t=easing(active.config.easing,raw);Vector3.LerpToRef(active.from,active.to,t,monster.root.position);if(active.config.mode==='ghost'){const wave=Math.sin(raw*Math.PI*2*active.config.floatCycles);monster.root.position.y+=wave*active.config.floatAmplitude;monster.root.position.x+=Math.sin(raw*Math.PI*active.config.floatCycles)*active.config.floatAmplitude*.35}else if(active.config.mode==='bigJump')monster.root.position.y+=Math.sin(raw*Math.PI)*active.config.jumpHeight;else monster.root.position.y+=Math.abs(Math.sin(raw*Math.PI*active.config.hopCount))*active.config.jumpHeight;if(raw>=1){monster.root.position.copyFrom(active.to);motionsRef.current.delete(id)}});context.scene.render()});
  return()=>{canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);canvas.removeEventListener('wheel',wheel);document.removeEventListener('mousemove',locked);window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('resize',resize);renderedRef.current.forEach(item=>item.dispose());renderedRef.current.clear();panel.dispose();context.dispose();sceneRef.current=null};
 },[]);

 const renderField=(nextField:Battlefield)=>{const scene=sceneRef.current;if(!scene)return;renderedRef.current.forEach(item=>item.dispose());renderedRef.current.clear();motionsRef.current.clear();gridRef.current?.getChildMeshes().forEach(mesh=>mesh.dispose());const material=new StandardMaterial(`movementGrid_${Date.now()}`,scene);material.diffuseColor=new Color3(.12,.45,.68);material.emissiveColor=new Color3(.03,.15,.24);material.alpha=.34;const rowCount=Math.max(5,...nextField.monsters.map(item=>item.row+3),...rulesRef.current.map(rule=>rule.startRow+2));for(let row=0;row<rowCount;row++)for(let column=0;column<nextField.width;column++){const cell=MeshBuilder.CreateBox(`cell_${row}_${column}`,{width:nextField.cellSize-.08,depth:Math.min(nextField.cellSize,nextField.rowSpacing)-.08,height:.035},scene);cell.position.set((column+.5-nextField.width/2)*nextField.cellSize,-2.105,-row*nextField.rowSpacing);cell.material=material;cell.parent=gridRef.current;cell.isPickable=false}nextField.monsters.forEach(item=>{const config=configsRef.current[item.monsterConfigKey];if(!config)return;const stripeKey=stripeForRow(rulesRef.current,item.row,item.monsterStripePresetKey||config.monsterStripePresetKey||'');const monster=createLayeredMonster(scene,`movement_${item.id}`);monster.load(config,monsterStripesRef.current[stripeKey]||null,stripesRef.current);monster.root.position.copyFrom(displayedPositionOf(nextField,item,config));renderedRef.current.set(item.id,monster)})};
 useEffect(()=>{if(field&&sceneRef.current&&Object.keys(configs).length)renderField(field)},[activeId,configs]);

 const patchPlacements=(next:Monster[])=>activeId&&setPlacements(all=>({...all,[activeId]:next}));
 const moveMonster=(next:Monster)=>{if(!field||!selected)return;const controller=renderedRef.current.get(selected.id),config=configsRef.current[next.monsterConfigKey];if(controller&&config){const from=controller.root.position.clone(),stripeKey=stripeForRow(rulesRef.current,next.row,next.monsterStripePresetKey||config.monsterStripePresetKey||'');controller.setStripePreset(monsterStripesRef.current[stripeKey]||null,stripesRef.current);motionsRef.current.set(selected.id,{from,to:displayedPositionOf(field,next,config),elapsed:0,config:{...motion}})}patchPlacements(field.monsters.map(item=>item.id===selected.id?next:item))};
 const patchMonster=(patch:Partial<Monster>,animate=false)=>{if(!selected||!field)return;const next={...selected,...patch},items=field.monsters.map(item=>item.id===selected.id?next:item);if(animate)moveMonster(next);else{patchPlacements(items);queueMicrotask(()=>renderField({...field,monsters:items}))}};
 const applyRules=(next:StripeRule[])=>{setRulesByField(all=>({...all,[activeId]:next}));rulesRef.current=next;queueMicrotask(()=>field&&renderField(field))};
 const patchRule=(id:string,patch:Partial<StripeRule>)=>applyRules(rules.map(rule=>rule.id===id?{...rule,...patch}:rule).sort((a,b)=>a.startRow-b.startRow));
 const patchMotion=(patch:Partial<MotionConfig>)=>{if(!selected)return;const key=selected.monsterConfigKey;setMovementConfigs(all=>({...all,[key]:normalizeMotion(key,{...(all[key]||defaultMotion(key)),...patch})}))};
 const saveMovements=async()=>{try{const payload=Object.fromEntries(Object.entries(movementConfigs).map(([key,value])=>[key,normalizeMotion(key,value)]));const response=await requestDevServer(MOVEMENT_API,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok||result.success===false)throw new Error(result.errors?.[0]||result.message||`HTTP ${response.status}`);setMessage(`已保存 ${Object.keys(payload).length} 个怪物移动配置到 config/monsterMovementConfigs.json。`)}catch(error){setMessage(`保存失败：${String(error)}`)}};
 const addMonster=()=>{if(!field)return;const key=Object.keys(configs)[0];if(!key)return;const item:Monster={id:uid(),monsterConfigKey:key,monsterStripePresetKey:configs[key]?.monsterStripePresetKey||'',positionMode:'grid',slots:1,row:0,column:0},items=[...field.monsters,item];patchPlacements(items);setSelectedId(item.id);queueMicrotask(()=>renderField({...field,monsters:items}))};
 const reset=()=>{if(!source)return;const items=cloneMonsters(source.monsters);patchPlacements(items);setSelectedId(items[0]?.id||'');queueMicrotask(()=>renderField({...source,monsters:items}))};
 return <div className="movement-lab" style={{height:'100vh',padding:14,display:'grid',gridTemplateColumns:'440px minmax(0,1fr)',gap:14}}>
  <aside style={{overflow:'auto',display:'flex',flexDirection:'column',gap:12}}>
   <div><h2 style={{margin:'0 0 5px'}}>怪物移动动画 Lab</h2><div style={{color:'#8291a8',fontSize:12}}>位置输入在 Enter 或失焦时应用，并触发怪物移动动画。</div></div>
   <section style={section}><label>战场配置</label><select value={activeId} onChange={event=>setActiveId(event.target.value)}>{Object.values(battlefields).map(item=><option key={item.id} value={item.id}>{item.name} · {item.id}</option>)}</select>{field&&<div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:7,marginTop:9,color:'#aab7ca',fontSize:12}}><span>{field.width} 列</span><span>格宽 {field.cellSize}</span><span>行距 {field.rowSpacing}</span></div>}</section>
   <section style={section}><strong>当前怪物移动配置</strong><div style={{color:'#8291a8',fontSize:12,marginTop:5}}>{selected?`${configs[selected.monsterConfigKey]?.name||selected.monsterConfigKey} · ${selected.monsterConfigKey}`:'请先选择怪物'}</div>{selected&&<><label>移动方式</label><select value={motion.mode} onChange={event=>patchMotion({mode:event.target.value as MotionConfig['mode']})}><option value="ghost">幽灵漂浮</option><option value="bigJump">大跳</option><option value="hopping">蹦蹦跳跳</option></select><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><div><label>时长 / 秒</label><CommitNumberInput min={.05} step={.05} value={motion.duration} onCommit={value=>patchMotion({duration:Math.max(.05,value)})}/></div><div><label>缓动</label><select value={motion.easing} onChange={event=>patchMotion({easing:event.target.value as MotionConfig['easing']})}><option value="easeInOut">平滑进出</option><option value="linear">线性</option><option value="easeOutBack">越界回弹</option></select></div>{motion.mode==='ghost'?<><div><label>漂浮幅度</label><CommitNumberInput min={0} step={.05} value={motion.floatAmplitude} onCommit={value=>patchMotion({floatAmplitude:Math.max(0,value)})}/></div><div><label>漂浮周期</label><CommitNumberInput min={1} step={1} value={motion.floatCycles} onCommit={value=>patchMotion({floatCycles:positiveInt(value)})}/></div></>:<><div><label>跳跃高度</label><CommitNumberInput min={0} step={.1} value={motion.jumpHeight} onCommit={value=>patchMotion({jumpHeight:Math.max(0,value)})}/></div>{motion.mode==='hopping'&&<div><label>跳跃次数</label><CommitNumberInput min={1} step={1} value={motion.hopCount} onCommit={value=>patchMotion({hopCount:positiveInt(value)})}/></div>}</>}</div></>}</section>
   <section style={section}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><strong>距离条纹规则</strong><button onClick={()=>applyRules([...rules,{id:uid(),startRow:Math.max(1,...rules.map(rule=>rule.startRow+1)),monsterStripePresetKey:Object.keys(monsterStripes)[0]||''}])}>添加规则</button></div>{rules.map(rule=><div key={rule.id} style={{display:'grid',gridTemplateColumns:'92px 1fr 58px',gap:7,alignItems:'end'}}><div><label>从第几行</label><CommitNumberInput min={1} step={1} value={rule.startRow} onCommit={value=>patchRule(rule.id,{startRow:positiveInt(value)})}/></div><div><label>怪物条纹</label><select value={rule.monsterStripePresetKey} onChange={event=>patchRule(rule.id,{monsterStripePresetKey:event.target.value})}>{Object.entries(monsterStripes).map(([key,preset])=><option key={key} value={key}>{preset.name||key}</option>)}</select></div><button onClick={()=>applyRules(rules.filter(item=>item.id!==rule.id))}>删除</button></div>)}</section>
   <section style={section}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong>怪物</strong><button onClick={addMonster}>添加怪物</button></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,marginTop:8}}><button onClick={reset}>恢复战场默认</button><button onClick={()=>{if(!field)return;patchPlacements([]);renderField({...field,monsters:[]})}}>清空</button></div><div style={{display:'flex',flexDirection:'column',gap:6,marginTop:9}}>{field?.monsters.map((item,index)=><button key={item.id} onClick={()=>setSelectedId(item.id)} style={{textAlign:'left',borderColor:item.id===selectedId?'#65a8ff':'#3a4961',background:item.id===selectedId?'#183b61':'#202b3d'}}>{index+1}. {configs[item.monsterConfigKey]?.name||item.monsterConfigKey} · 第 {item.row+1} 行</button>)}</div></section>
   {selected&&<section style={section}><label>怪物配置</label><select value={selected.monsterConfigKey} onChange={event=>{const key=event.target.value;patchMonster({monsterConfigKey:key,monsterStripePresetKey:configs[key]?.monsterStripePresetKey||''})}}>{Object.entries(configs).map(([key,config])=><option key={key} value={key}>{config.name||key} · {key}</option>)}</select><label>位置模式</label><select value={selected.positionMode} onChange={event=>patchMonster({positionMode:event.target.value==='center'?'center':'grid'},true)}><option value="grid">格子定位</option><option value="center">绝对居中</option></select><label>所在行（从 1 开始）</label><CommitNumberInput min={1} step={1} value={selected.row+1} onCommit={value=>patchMonster({row:indexInt(value-1)},true)}/>{selected.positionMode==='grid'&&<><label>占用格数</label><CommitNumberInput min={1} step={1} value={selected.slots} onCommit={value=>patchMonster({slots:positiveInt(value)},true)}/><label>所在列（从 1 开始）</label><CommitNumberInput min={1} step={1} value={selected.column+1} onCommit={value=>patchMonster({column:indexInt(value-1)},true)}/></>}<button style={{width:'100%',marginTop:10}} onClick={()=>{if(!field)return;const items=field.monsters.filter(item=>item.id!==selected.id);patchPlacements(items);queueMicrotask(()=>renderField({...field,monsters:items}))}}>删除此怪物</button></section>}
   <section style={section}><button style={{width:'100%'}} onClick={()=>void saveMovements()}>保存全部怪物移动配置</button><div style={{color:'#9dacbf',fontSize:12,lineHeight:1.5,marginTop:8}}>{message}</div></section>
  </aside>
  <main ref={stageRef} style={{minWidth:0,position:'relative',border:'1px solid #273348',borderRadius:8,overflow:'hidden',background:'#080d14'}}><canvas ref={canvasRef} style={{width:'100%',height:'100%',display:'block'}}/><div style={{position:'absolute',left:12,bottom:10,color:'#c1cede',fontSize:12,pointerEvents:'none'}}>提交新位置后，怪物从当前点移动到目标格 · 条纹按目标行更新</div></main>
 </div>;
};

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
