import { Color3,Color4,Engine,Material,MeshBuilder,SolidParticleSystem,StandardMaterial,Texture,TransformNode,Vector3,type Scene } from '@babylonjs/core';
import { getParticleMotionDefinition,type MotionParameterValues,type ParticleMotionRuntimeConfig } from '@/core/particle-motion';
import type { ParticleVisualPreset } from '@/core/particle';
import type { MonsterStatusParticleController,MonsterStatusParticlePreset } from './types';
import { resolvePublicResourceUrl } from '@/core/resources/appAssetUrl.ts';

const randomFactory=(initial:number)=>{let seed=initial>>>0;return()=>{seed+=0x6d2b79f5;let value=seed;value=Math.imul(value^(value>>>15),value|1);value^=value+Math.imul(value^(value>>>7),value|61);return((value^(value>>>14))>>>0)/4294967296}};
const publicUrl=(path:string)=>resolvePublicResourceUrl(path);
const sampleSize=(preset:ParticleVisualPreset,time:number)=>{if(!preset.sizeGradientsEnabled||!preset.sizeGradients.length)return preset.baseSize;const values=[...preset.sizeGradients].sort((a,b)=>a.offset-b.offset),right=values.findIndex(item=>item.offset>=time);if(right<0)return values[values.length-1].size;if(right===0)return values[0].size;const left=values[right-1],next=values[right],q=(time-left.offset)/Math.max(.0001,next.offset-left.offset);return left.size+(next.size-left.size)*q};
const sampleColor=(preset:ParticleVisualPreset,time:number)=>{const base=preset.baseColor;if(!preset.colorGradientsEnabled||preset.colorMode==='texture'||!preset.colorGradients.length)return new Color4(base.r,base.g,base.b,base.a);const values=[...preset.colorGradients].sort((a,b)=>a.offset-b.offset),right=values.findIndex(item=>item.offset>=time);if(right<0){const color=values[values.length-1].color;return new Color4(color.r,color.g,color.b,color.a)}if(right===0){const color=values[0].color;return new Color4(color.r,color.g,color.b,color.a)}const left=values[right-1],next=values[right],q=(time-left.offset)/Math.max(.0001,next.offset-left.offset);return new Color4(left.color.r+(next.color.r-left.color.r)*q,left.color.g+(next.color.g-left.color.g)*q,left.color.b+(next.color.b-left.color.b)*q,left.color.a+(next.color.a-left.color.a)*q)};

export const createMonsterStatusParticle=(scene:Scene,parent:TransformNode,preset:MonsterStatusParticlePreset,visual:ParticleVisualPreset):MonsterStatusParticleController=>{
 const definition=getParticleMotionDefinition(preset.motionModeId),capacity=Math.max(1,Math.round(preset.capacity)),runtime:ParticleMotionRuntimeConfig={capacity,activeCount:Math.max(0,Math.min(capacity,Math.round(preset.activeCount))),timeScale:Math.max(.01,preset.timeScale),sizeScale:Math.max(.01,preset.sizeScale),fieldRadius:Math.max(.05,preset.fieldRadius),seed:Math.round(preset.seed)};
 const emitter=new TransformNode('statusParticle_'+preset.presetKey+'_'+Date.now(),scene),anchorY=preset.anchor==='feet'?-2:preset.anchor==='head'?2:0,localOffset=new Vector3(preset.offset.x,anchorY+preset.offset.y,preset.offset.z);
 if(preset.followMonster&&preset.anchor!=='world'){emitter.parent=parent;emitter.position.copyFrom(localOffset)}else{parent.computeWorldMatrix(true);emitter.position.copyFrom(parent.getAbsolutePosition()).addInPlace(localOffset)}
 const shape=MeshBuilder.CreatePlane('statusParticleShape',{size:1},scene),sps=new SolidParticleSystem('statusParticleSps_'+preset.presetKey,scene,{updatable:true});sps.billboard=true;sps.addShape(shape,capacity);shape.dispose();const mesh=sps.buildMesh();mesh.parent=emitter;mesh.isPickable=false;
 const material=new StandardMaterial('statusParticleMaterial_'+preset.presetKey,scene),texture=new Texture(publicUrl(visual.texturePath),scene);texture.hasAlpha=true;material.diffuseTexture=texture;material.emissiveTexture=texture;material.useAlphaFromDiffuseTexture=true;material.emissiveColor=Color3.White();material.diffuseColor=Color3.White();material.disableLighting=true;material.backFaceCulling=false;material.alphaMode=visual.blendMode==='overwrite'?Engine.ALPHA_DISABLE:visual.blendMode==='add'?Engine.ALPHA_ADD:visual.blendMode==='multiply'?Engine.ALPHA_MULTIPLY:Engine.ALPHA_COMBINE;if(visual.blendMode==='overwrite'){material.useAlphaFromDiffuseTexture=false;material.transparencyMode=Material.MATERIAL_OPAQUE}mesh.material=material;
 const random=randomFactory(runtime.seed),context={random,runtime},parameters=preset.motionParameters as MotionParameterValues,states=Array.from({length:capacity},()=>definition.createState(context,parameters)),sizeRandom=randomFactory(runtime.seed^0x73697a65),baseSize=Math.max(.0001,visual.baseSize),sizeFactors=Array.from({length:capacity},()=>Math.max(.0001,visual.minSize+sizeRandom()*(visual.maxSize-visual.minSize))/baseSize),atlasRandom=randomFactory(runtime.seed^0x51f15e),atlasIds=Array.from({length:capacity},()=>{const sheet=visual.spriteSheet;if(!sheet)return 0;const count=Math.max(1,sheet.endCellID-sheet.startCellID+1);return sheet.randomStartCell?sheet.startCellID+Math.floor(atlasRandom()*count):sheet.startCellID});
 let elapsed=0,paused=false,stack=1,disposed=false;
 const activeCount=()=>Math.min(capacity,Math.max(0,Math.round(runtime.activeCount*stack)));
 const updateAtlas=()=>{const sheet=visual.spriteSheet;if(!sheet)return;const size=texture.getSize(),columns=Math.max(1,Math.floor(size.width/sheet.cellWidth)),rows=Math.max(1,Math.floor(size.height/sheet.cellHeight)),last=columns*rows-1,count=Math.max(1,sheet.endCellID-sheet.startCellID+1),frame=sheet.playbackMode==='loop'?Math.floor(elapsed*sheet.framesPerSecond):0;sps.particles.forEach((particle,index)=>{const cell=Math.min(last,Math.max(0,sheet.startCellID+(atlasIds[index]-sheet.startCellID+frame)%count)),column=cell%columns,row=Math.floor(cell/columns);particle.uvs.set(column/columns,row/rows,(column+1)/columns,(row+1)/rows)})};
 sps.initParticles=()=>sps.particles.forEach((particle,index)=>{definition.initialize(particle,states[index],context,parameters);const t=(index*.013)%1;particle.color=sampleColor(visual,t);particle.scaling.setAll(sampleSize(visual,t)*sizeFactors[index]*runtime.sizeScale);if(index>=activeCount())particle.color.a=0});sps.initParticles();updateAtlas();sps.setParticles();
 const observer=scene.onBeforeRenderObservable.add(()=>{if(paused||disposed)return;const dt=Math.min(scene.getEngine().getDeltaTime()/1000,.05)*runtime.timeScale;elapsed+=dt;const updateContext={random,runtime,deltaSeconds:dt,elapsedSeconds:elapsed};sps.updateParticle=particle=>{if(particle.idx<activeCount()){definition.update(particle,states[particle.idx],updateContext,parameters);const t=(elapsed*.5+particle.idx*.013)%1;particle.color=sampleColor(visual,t);particle.scaling.setAll(sampleSize(visual,t)*sizeFactors[particle.idx]*runtime.sizeScale)}else if(particle.color)particle.color.a=0;return particle};updateAtlas();sps.setParticles()});
 return{pause:()=>{paused=true},resume:()=>{paused=false},setStack:value=>{stack=Math.max(1,Math.round(value))},dispose:()=>{if(disposed)return;disposed=true;scene.onBeforeRenderObservable.remove(observer);sps.dispose();emitter.dispose();material.dispose(false,true)}};
};
