const { app, BrowserWindow } = require('electron');
const fs = require('node:fs');
app.commandLine.appendSwitch('use-angle', 'swiftshader');
app.commandLine.appendSwitch('enable-unsafe-swiftshader');
const reportPath = 'node_modules/.cache/scene-environment-browser.json';
const report = value => { fs.mkdirSync('node_modules/.cache', { recursive: true }); fs.writeFileSync(reportPath, JSON.stringify(value, null, 2)); };
app.whenReady().then(async () => {
  const window = new BrowserWindow({ show: false, width: 1440, height: 1000, webPreferences: { offscreen: true, backgroundThrottling: false } });
  try {
    await window.loadURL(process.env.SCENE_ENVIRONMENT_TEST_URL);
    const result = await window.webContents.executeJavaScript(`(async () => {
      const check = (value, message) => { if (!value) throw new Error(message); };
      const wait = async predicate => { for (let i=0;i<600;i++) { if (predicate()) return; await new Promise(r=>setTimeout(r,50)); } throw new Error(document.querySelector('#status')?.textContent || 'Timeout'); };
      const ready = () => !document.querySelector('#load').disabled && document.querySelector('#status').textContent.includes('已通过');
      const select = name => { const row = [...document.querySelectorAll('.editor-hierarchy-row')].find(row=>row.querySelector('.editor-hierarchy-label').textContent === name); check(row, 'Missing row '+name); row.click(); };
      const input = label => document.querySelector('[aria-label="'+label+'"]');
      const button = text => [...document.querySelectorAll('button')].find(b=>b.textContent === text);
      const set = (label, value) => { const element=input(label); check(element,'Missing field '+label); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(element,value); element.dispatchEvent(new Event('input',{bubbles:true})); };
      const draft = () => { const value=JSON.parse(document.querySelector('#preset-json').textContent); return value.scene || value; };
      await wait(ready);
      const verification = await import('/@id/virtual:scene-environment-verification');
      const runtime = () => verification.scene();
      const width = () => runtime().getMeshByName('box').getBoundingInfo().boundingBox.extendSize.x * 2;
      const preset = document.querySelector('#preset'); preset.value='child'; preset.dispatchEvent(new Event('change',{bubbles:true})); document.querySelector('#load').click();
      await wait(()=>ready() && document.querySelector('#current-scene-key').value==='child');
      const boxRow = [...document.querySelectorAll('.editor-hierarchy-row')].find(row=>row.querySelector('.editor-hierarchy-label')?.textContent==='Browser Box');
      check(boxRow, 'Missing box row for context menu');
      boxRow.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,button:2,clientX:120,clientY:120}));
      await wait(()=>button('添加模型'));
      button('添加模型').click();
      await wait(()=>button('cuboid2.glb'));
      button('cuboid2.glb').click();
      await wait(()=>ready() && draft().models.length===2 && draft().models[1].modelPath.endsWith('cuboid2.glb'));
      check(draft().models[1].parentId==='object:box','Added model did not inherit the context parent');
      check(runtime().getTransformNodeByName('child:'+draft().models[1].id).parent===runtime().getMeshByName('box'),'Async model was not attached to its declared parent');
      button('撤销').click(); await wait(()=>ready() && draft().models.length===1);
      select('Browser Hemi'); await wait(()=>input('地面颜色')); check(!input('阴影预设（清空关闭阴影）'),'Hemi exposed shadow');
      select('Browser Sun'); await wait(()=>input('阴影预设（清空关闭阴影）')); check(!input('照明范围'),'Sun exposed point range');
      select('Browser Point'); await wait(()=>input('照明范围'));
      select('Browser Model'); await wait(()=>input('模型路径（GLB / GLTF）'));
      check(input('旋转（弧度） X')?.value==='0' && input('缩放 Y')?.value==='1','Optional vector defaults not shown per axis');
      set('旋转（弧度） X','0.5'); set('缩放 Y','2');
      await wait(()=>!button('应用并预览').disabled); button('应用并预览').click();
      await wait(()=>ready() && draft().models[0].rotation?.[0]===0.5 && draft().models[0].scaling?.[1]===2);
      button('撤销').click(); await wait(()=>ready() && draft().models[0].rotation===undefined && draft().models[0].scaling===undefined);
      const transformCount = runtime().transformNodes.length;
      set('模型路径（GLB / GLTF）','resources/Model/GLB/scene-environment-test-missing.glb'); await new Promise(r=>setTimeout(r,50)); button('应用并预览').click();
      await wait(()=>document.querySelector('#status').textContent.includes('加载失败'));
      check(runtime().getMeshByName('box').isEnabled(), 'Failed candidate hid previous preview');
      check(runtime().transformNodes.length===transformCount,'Failed model leaked transform nodes');
      button('撤销').click(); await wait(()=>ready() && draft().models[0].modelPath.endsWith('cuboid.glb'));
      select('Browser Cylinder'); await wait(()=>input('圆周细分')); check(!input('深度'),'Cylinder exposed box depth');
      select('Browser Box'); await wait(()=>input('宽度'));
      set('宽度','-3'); await wait(()=>!button('应用并预览').disabled); button('应用并预览').click(); await wait(()=>document.querySelector('[role=alert]')); check(draft().objects[0].geometry.width===2,'Invalid edit changed draft');
      set('宽度','6'); await new Promise(r=>setTimeout(r,50)); button('应用并预览').click(); await wait(()=>ready() && draft().objects[0].geometry.width===6); await wait(()=>input('宽度')?.value==='6');
      check(Math.abs(width()-6)<0.001,'Geometry was not rebuilt');
      button('撤销').click(); await wait(()=>ready() && draft().objects[0].geometry.width===2); await wait(()=>input('宽度')?.value==='2');
      check(Math.abs(width()-2)<0.001,'Undo did not rebuild geometry');
      button('重做').click(); await wait(()=>ready() && draft().objects[0].geometry.width===6); await wait(()=>input('宽度')?.value==='6');
      check(Math.abs(width()-6)<0.001,'Redo did not rebuild geometry');
      button('撤销').click(); button('重做').click(); await wait(()=>ready() && draft().objects[0].geometry.width===6);
      // Create a persisted hierarchy through the actual menus/Inspector.
      const row = name => [...document.querySelectorAll('.editor-hierarchy-row')].find(item => item.querySelector('.editor-hierarchy-label')?.textContent===name);
      const context = async (element, label) => { element.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,button:2,clientX:130,clientY:180})); await wait(()=>button(label)); button(label).click(); };
      await context(row('Browser Model'), '添加 Socket 挂点');
      await wait(()=>ready() && draft().transformNodes.length===1);
      check(runtime().getTransformNodeByName(draft().transformNodes[0].id).parent===runtime().getTransformNodeByName('child:model'),'Forward reference to an async model parent was not resolved');
      button('撤销').click(); await wait(()=>ready() && draft().transformNodes.length===0);
      await context(document.querySelector('.environment-hierarchy-menu-area'), '添加空节点');
      await wait(()=>ready() && draft().transformNodes.length===1 && input('用途'));
      set('名称','动画根节点'); set('位置 X','10'); await wait(()=>!button('应用并预览').disabled); button('应用并预览').click();
      await wait(()=>ready() && row('动画根节点'));
      await context(row('动画根节点'), '添加 Rig');
      await wait(()=>ready() && draft().transformNodes.length===2 && row('Rig 1'));
      await context(row('Rig 1'), '添加 Socket 挂点');
      await wait(()=>ready() && draft().transformNodes.length===3 && row('Socket 挂点 1'));
      const socketId = 'transform:' + draft().transformNodes[2].id;
      check(draft().transformNodes[2].parentId==='transform:'+draft().transformNodes[1].id,'Socket parent was not persisted');
      select('动画根节点'); await wait(()=>input('父节点')); check(input('父节点').options.length===5,'Root parent options should exclude its descendants and lights');
      select('Browser Box'); await wait(()=>input('父节点'));
      const before = runtime().getMeshByName('box'); before.computeWorldMatrix(true); const beforePosition = before.getAbsolutePosition().asArray();
      input('父节点').value=socketId; input('父节点').dispatchEvent(new Event('change',{bubbles:true}));
      await wait(()=>!button('应用父节点').disabled); button('应用父节点').click();
      await wait(()=>ready() && draft().objects[0].parentId===socketId);
      const assertPosition = expected => { const mesh=runtime().getMeshByName('box'); mesh.computeWorldMatrix(true); check(mesh.getAbsolutePosition().asArray().every((value,i)=>Math.abs(value-expected[i])<0.001),'World position changed incorrectly'); };
      assertPosition(beforePosition);
      check(row('Browser Box').closest('.editor-hierarchy-branch').parentElement.closest('.editor-hierarchy-branch').querySelector('.editor-hierarchy-label').textContent==='Socket 挂点 1','Tree does not reflect the declared parent');
      select('动画根节点'); await wait(()=>input('位置 X')); set('位置 X','15'); await wait(()=>!button('应用并预览').disabled); button('应用并预览').click();
      await wait(()=>ready() && draft().transformNodes[0].position[0]===15); assertPosition([beforePosition[0]+5,beforePosition[1],beforePosition[2]]);
      button('撤销').click(); await wait(()=>ready() && draft().transformNodes[0].position[0]===10); assertPosition(beforePosition);
      button('撤销').click(); await wait(()=>ready() && !draft().objects[0].parentId); assertPosition(beforePosition);
      button('重做').click(); await wait(()=>ready() && draft().objects[0].parentId===socketId); assertPosition(beforePosition);
      await context(row('Browser Box'), '移至根层级（保持世界姿态）');
      await wait(()=>ready() && draft().objects[0].parentId===null); assertPosition(beforePosition);
      button('撤销').click(); await wait(()=>ready() && draft().objects[0].parentId===socketId);
      const dragNode = async (sourceName, targetName, placement, valid=true) => {
        const source=row(sourceName); const transfer=new DataTransfer();
        source.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:transfer}));
        await new Promise(r=>setTimeout(r,30));
        const target=targetName ? row(targetName) : document.querySelector('.editor-hierarchy-root-drop');
        const bounds=target.getBoundingClientRect(); const ratio=placement==='before' ? .1 : placement==='after' ? .9 : .5;
        const options={bubbles:true,cancelable:true,dataTransfer:transfer,clientX:bounds.left+30,clientY:bounds.top+bounds.height*ratio};
        target.dispatchEvent(new DragEvent('dragover',options));
        await new Promise(r=>setTimeout(r,30));
        check(target.classList.contains(targetName ? 'drop-invalid' : 'invalid')===!valid,'Unexpected drop validation');
        target.dispatchEvent(new DragEvent('drop',options));
        source.dispatchEvent(new DragEvent('dragend',{bubbles:true,dataTransfer:transfer}));
      };
      await dragNode('Browser Cylinder','Socket 挂点 1','inside');
      await wait(()=>ready() && draft().objects[2].parentId===socketId);
      await dragNode('Browser Cylinder','Browser Box','before');
      await wait(()=>ready() && draft().objects[2].order<draft().objects[0].order);
      check(row('Socket 挂点 1').closest('.editor-hierarchy-branch').querySelectorAll('.editor-hierarchy-row')[1].querySelector('.editor-hierarchy-label').textContent==='Browser Cylinder','Before-drop did not reorder the tree');
      button('撤销').click(); await wait(()=>ready() && draft().objects[0].order<draft().objects[2].order);
      button('重做').click(); await wait(()=>ready() && draft().objects[2].order<draft().objects[0].order);
      const validDraft=JSON.stringify(draft());
      await dragNode('动画根节点','Browser Box','inside',false);
      check(JSON.stringify(draft())===validDraft,'Invalid cyclic drop changed the document');
      await dragNode('Browser Cylinder',null,'root-end');
      await wait(()=>ready() && draft().objects[2].parentId===null);
      button('撤销').click(); await wait(()=>ready() && draft().objects[2].parentId===socketId);
      // Only authored objects belong in the tree, regardless of GLTF nesting depth.
      check(![...document.querySelectorAll('.editor-hierarchy-row')].some(item=>item.dataset.objectId.includes('/render:')),'Imported render nodes leaked into the authoring tree');
      check(row('Browser Model').closest('.editor-hierarchy-branch').querySelectorAll('.editor-hierarchy-row').length===1,'Model without authored children must be one row');
      check(row('Browser Model').querySelector('.editor-hierarchy-chevron').classList.contains('empty'),'Model incorrectly shows an expandable internal hierarchy');
      select('Browser Model'); await wait(()=>input('模型路径（GLB / GLTF）'));
      const assetSection=[...document.querySelectorAll('.editor-inspector-section-heading')].find(b=>b.querySelector('strong')?.textContent==='模型资产校正');
      check(assetSection,'Missing asset properties panel'); assetSection.click(); await wait(()=>input('原点偏移 X'));
      check(input('原点偏移 X').readOnly && input('资产缩放 X').readOnly,'Shared asset properties should retain their read-only ownership');
      check(Number(input('资产缩放 X').value)===runtime().getTransformNodeByName('child:model:asset-profile').scaling.x,'Asset panel did not reflect the loaded model');
      check(!row('场景配置').draggable,'Scene config should not be draggable');
      // Marker visibility is local UI state, not a declaration edit or history entry.
      const authored=JSON.stringify(draft());
      const handles=()=>runtime().meshes.filter(mesh=>mesh.name.startsWith('editor:marker:'));
      check(handles().length===3 && handles().every(mesh=>mesh.isEnabled() && mesh.isPickable && mesh.doNotSerialize),'Missing editor-only pickable markers');
      button('挂点标记').click(); check(handles().every(mesh=>!mesh.isEnabled()),'Marker toggle did not hide handles');
      check(JSON.stringify(draft())===authored,'Marker visibility leaked into the declaration');
      await dragNode('Browser Cylinder','Browser Box','after');
      await wait(()=>ready() && draft().objects[0].order<draft().objects[2].order);
      check(handles().every(mesh=>!mesh.isEnabled()),'Preview rebuild lost marker visibility');
      button('挂点标记').click(); check(handles().every(mesh=>mesh.isEnabled()),'Markers did not reappear');
      document.querySelector('#save-preset').click(); await wait(()=>document.querySelector('#status').textContent.includes('已保存到'));
      return { dragReparent: true, siblingOrder: true, rejectedCycle: true, declarationOnlyTree: true, editorMarkers: true, hierarchy: true, reparentWorldPose: true, parentTransform: true, hierarchyUndoRedo: true, fields: true, validation: true, rebuildSelection: true, undoRedo: true, modelFailureCleanup: true, rapidHistory: true, save: true };
    })()`);
    await new Promise(resolve => { window.webContents.once('did-finish-load', resolve); window.reload(); });
    await window.webContents.executeJavaScript(`(async()=>{
      for(let i=0;i<600;i++) { const select=document.querySelector('#preset'); if(select?.options.length && !document.querySelector('#load').disabled) { select.value='child'; select.dispatchEvent(new Event('change',{bubbles:true})); document.querySelector('#load').click(); break; } await new Promise(r=>setTimeout(r,50)); }
      for(let i=0;i<600;i++) { if(document.querySelector('#current-scene-key').value==='child' && !document.querySelector('#load').disabled) { const p=JSON.parse(document.querySelector('#preset-json').textContent).scene; if(p.objects[0].geometry.width!==6) throw new Error('Saved width not restored'); if(p.transformNodes.length!==3 || p.objects[0].parentId!=='transform:'+p.transformNodes[2].id) throw new Error('Saved hierarchy not restored'); if(p.objects[2].parentId!==p.objects[0].parentId || !(p.objects[0].order<p.objects[2].order)) throw new Error('Saved drag order not restored'); return; } await new Promise(r=>setTimeout(r,50)); } throw new Error('Refresh timeout');
    })()`);
    await window.webContents.executeJavaScript(`(async()=>{ const row=[...document.querySelectorAll('.editor-hierarchy-row')].find(item=>item.querySelector('.editor-hierarchy-label')?.textContent==='Browser Model'); if(!row) throw new Error('Missing model row for screenshot'); row.click(); for(let i=0;i<40;i++){if(document.querySelector('[aria-label="缩放 X"]')) return; await new Promise(resolve=>setTimeout(resolve,50));} throw new Error('Model vector inputs did not render'); })()`);
    const capture = await window.webContents.capturePage();
    fs.writeFileSync('node_modules/.cache/scene-environment-browser.png', capture.toPNG());
    await window.loadURL(process.env.SCENE_ENVIRONMENT_PRODUCTION_URL);
    await window.webContents.executeJavaScript(`(async()=>{
      for(let i=0;i<600;i++) { const select=document.querySelector('#preset'); if(select?.options.length) { if(![...select.options].some(o=>o.value==='minimal-city')) throw new Error('Production did not read bundled catalog'); select.value='minimal-city'; select.dispatchEvent(new Event('change',{bubbles:true})); document.querySelector('#load').disabled=false; document.querySelector('#load').click(); break; } await new Promise(r=>setTimeout(r,50)); }
      for(let i=0;i<600;i++) { if(document.querySelector('#current-scene-key')?.value==='minimal-city' && !document.querySelector('#load').disabled) return; await new Promise(r=>setTimeout(r,50)); } throw new Error('Production catalog preview failed: '+document.querySelector('#status')?.textContent);
    })()`);
    report({ ...result, reload: true, productionCatalog: true }); app.exit(0);
  } catch (error) { report({ error: String(error), stack: error.stack }); console.error(error); app.exit(1); }
});
setTimeout(()=>{report({error:'Browser regression timed out'});app.exit(1);},90000).unref();
