import { useEffect, useRef, useState } from 'react';
import { ArcRotateCamera, Color3, Color4, Engine, HemisphericLight, MeshBuilder, Scene, StandardMaterial, Vector3 } from '@babylonjs/core';
import { createBurstParticleEffect, getAllParticlePresets, hydrateParticlePresetStorage, type ParticleEditorPreset, type ParticleController, type ParticleEffectConfig } from '@/core/particle';
import { createModelEntity, type ModelEntity } from '@/core/model';

type ShootConfig = { modelPath: string; fireParticlePresetKey: string; fireIntervalMs: number; recoilAngleDeg: number; particleOffsetX: number; particleOffsetY: number; particleOffsetZ: number };
const defaults = (modelPath = ''): ShootConfig => ({ modelPath, fireParticlePresetKey: 'spark', fireIntervalMs: 250, recoilAngleDeg: -8, particleOffsetX: 0, particleOffsetY: 0, particleOffsetZ: 0 });
const configUrl = '/config/modelShootConfigs.json'; const apiUrl = '/api/model-shoot-configs';
const textureUrl = (path: string) => path.startsWith('/') ? path : `/resources/${path}`;

export const ModelShootLab = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null); const sceneRef = useRef<Scene | null>(null); const modelRef = useRef<ModelEntity | null>(null); const particleRef = useRef<ParticleController | null>(null); const baseRotationRef = useRef(new Vector3()); const configsRef = useRef<Record<string, ShootConfig>>({});
  const [assets, setAssets] = useState<string[]>([]); const [particles, setParticles] = useState<Record<string, ParticleEditorPreset>>({}); const [selectedPath, setSelectedPath] = useState(''); const [config, setConfig] = useState(defaults()); const [status, setStatus] = useState('正在初始化…'); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const engine = new Engine(canvas, true, { stencil: true }); const scene = new Scene(engine); sceneRef.current = scene; scene.clearColor = new Color4(0.025, 0.035, 0.052, 1); const camera = new ArcRotateCamera('shoot_camera', -Math.PI / 2, Math.PI / 2.5, 6, Vector3.Zero(), scene); camera.attachControl(canvas, true); const light = new HemisphericLight('shoot_light', new Vector3(.4, 1, .25), scene); light.intensity = 1.5; const ground = MeshBuilder.CreateGround('shoot_ground', { width: 30, height: 30 }, scene); const mat = new StandardMaterial('shoot_ground_mat', scene); mat.diffuseColor = new Color3(.07, .095, .14); ground.material = mat; engine.runRenderLoop(() => scene.render()); return () => { particleRef.current?.dispose(); modelRef.current?.dispose(); scene.dispose(); engine.dispose(); }; }, []);
  useEffect(() => { void hydrateParticlePresetStorage().then(() => setParticles(getAllParticlePresets())).catch(() => setStatus('Particle 预设读取失败')); void fetch(configUrl).then((response) => response.ok ? response.json() : {}).then((raw) => { if (raw && typeof raw === 'object') { configsRef.current = raw as Record<string, ShootConfig>; setConfig((current) => configsRef.current[current.modelPath] ?? current); } }).catch(() => undefined); void fetch('/api/model-assets').then((response) => response.json() as Promise<{ assets: string[] }>).then(({ assets: paths }) => { const glb = paths.filter((path) => /\.(glb|gltf)$/i.test(path)); setAssets(glb); if (glb[0]) selectModel(glb[0]); }); }, []);
  function selectModel(path: string) { const next = configsRef.current[path] ?? defaults(path); setSelectedPath(path); setConfig(next); setStatus(`准备开火：${decodeURIComponent(path.split('/').pop() ?? path)}`); setLoading(true); modelRef.current?.dispose(); if (sceneRef.current) void createModelEntity(sceneRef.current, path, { autoPlayAnimation: true }).then((model) => { model.root.rotationQuaternion = null; modelRef.current = model; baseRotationRef.current.copyFrom(model.root.rotation); setLoading(false); }); }
  const update = (patch: Partial<ShootConfig>) => { const next = { ...config, ...patch, modelPath: selectedPath }; setConfig(next); configsRef.current[selectedPath] = next; };
  const fire = () => { const model = modelRef.current; const scene = sceneRef.current; const preset = particles[config.fireParticlePresetKey]; if (!model || !scene || !preset) return; particleRef.current?.dispose(); const emitter = model.root.getAbsolutePosition().add(new Vector3(config.particleOffsetX, config.particleOffsetY, config.particleOffsetZ)); particleRef.current = createBurstParticleEffect(scene, ({ ...preset, texturePath: textureUrl(preset.texturePath), emitter, gravity: new Vector3(0, preset.gravityY, 0), minEmitBox: new Vector3(preset.minEmitBox.x, preset.minEmitBox.y, preset.minEmitBox.z), maxEmitBox: new Vector3(preset.maxEmitBox.x, preset.maxEmitBox.y, preset.maxEmitBox.z), direction1: new Vector3(preset.direction1.x, preset.direction1.y, preset.direction1.z), direction2: new Vector3(preset.direction2.x, preset.direction2.y, preset.direction2.z) } as unknown as ParticleEffectConfig)); particleRef.current.start(); model.root.rotation.copyFrom(baseRotationRef.current); model.root.rotation.z += config.recoilAngleDeg * Math.PI / 180; window.setTimeout(() => modelRef.current?.root.rotation.copyFrom(baseRotationRef.current), Math.min(config.fireIntervalMs, 400)); setStatus('已开火'); };
  const save = async () => { setSaving(true); try { const response = await fetch(apiUrl, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(configsRef.current) }); if (!response.ok) throw new Error('保存失败'); setStatus(`已保存 ${Object.keys(configsRef.current).length} 个模型的开火配置`); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } finally { setSaving(false); } };
  return <main className="shoot-lab"><header><div><h1>3D 模型射击动画 Lab</h1><span>{status}</span></div><select aria-label="选择模型" value={selectedPath} onChange={(event) => selectModel(event.target.value)}><option value="">选择模型…</option>{assets.map((path) => <option key={path} value={path}>{decodeURIComponent(path.replace('/resources/', ''))}</option>)}</select><button onClick={fire} disabled={loading || !selectedPath}>开火预览</button><button onClick={() => void save()} disabled={saving}>保存 Config</button></header><section className="viewport"><canvas ref={canvasRef} /></section><aside><h2>开火参数</h2><label><span>Particle 预设</span><select aria-label="开火粒子预设" value={config.fireParticlePresetKey} onChange={(event) => update({ fireParticlePresetKey: event.target.value })}>{Object.keys(particles).map((key) => <option key={key} value={key}>{particles[key].name || key}</option>)}</select></label><NumberControl label="开火间隔 ms" value={config.fireIntervalMs} min={1} max={60000} onChange={(fireIntervalMs) => update({ fireIntervalMs })} /><NumberControl label="后坐角度" value={config.recoilAngleDeg} min={-180} max={180} onChange={(recoilAngleDeg) => update({ recoilAngleDeg })} /><NumberControl label="粒子偏移 X" value={config.particleOffsetX} min={-100} max={100} onChange={(particleOffsetX) => update({ particleOffsetX })} /><NumberControl label="粒子偏移 Y" value={config.particleOffsetY} min={-100} max={100} onChange={(particleOffsetY) => update({ particleOffsetY })} /><NumberControl label="粒子偏移 Z" value={config.particleOffsetZ} min={-100} max={100} onChange={(particleOffsetZ) => update({ particleOffsetZ })} /><small>粒子预设直接来自 tools/particle-editor 的 Particle 配置。</small></aside></main>;
};
const NumberControl = ({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) => <label><span>{label}</span><input aria-label={label} type="number" value={value} min={min} max={max} step="0.1" onChange={(event) => onChange(Number(event.target.value))} /></label>;
